### ISSUE TITLE
Please provide per font css file

### ISSUE THREAD

**Issue by santhoshtr** [ramesh-k/malayalam-fonts#1]
Along with a single CSS file with all fonts, please provide css files for each font so that websites need not load unwanted code. Also the common usecase is using one or two fonts rather than all fonts.

For SMC fonts, you may refer CSS for each fonts given at SMC website:
https://smc.org.in/fonts/manjari.css

**Comment by ramesh-k** [comment]
Changes are live with [`malayalam-fonts@1.0.6-beta.3`](https://www.npmjs.com/package/malayalam-fonts/v/1.0.6-beta.3)
