### ISSUE TITLE
Add Nupuram, Malini, Chingam fonts

### ISSUE THREAD

**Issue by santhoshtr** [ramesh-k/malayalam-fonts#2]
* Malini CSS https://smc.org.in/fonts/malini.css
* Nupuram CSS https://smc.org.in/fonts/malini.css
* https://smc.org.in/fonts/nupuram.css

**Comment by ramesh-k** [comment]
Changes are live with [`malayalam-fonts@1.0.6-beta.3`](https://www.npmjs.com/package/malayalam-fonts/v/1.0.6-beta.3)
